package moclj;

import java.lang.constant.ClassDesc;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/// The runtime shared by every compiled class: the intern table mapping names
/// to [Var]s plus the handful of helpers that generated bytecode calls into.
///
/// The table maps a name to a Var, never straight to a value, so the value of a
/// name can change while its container stays the same object.
///
/// The methods below are the compilation targets of [Compiler]; they are public
/// because generated classes invoke them with `invokestatic`.
public final class RT {

    static final ClassDesc CLASS_DESC = ClassDesc.of(RT.class.getName());

    private static final Map<String, Var> VARS = new ConcurrentHashMap<>();

    private RT() {
    }

    /// Returns the Var interned under `name`, creating an unbound one when the
    /// name is new. Called once per referenced name from the `<clinit>` of a
    /// generated class, which then caches the result in a static field.
    public static Var var(String name) {
        return VARS.computeIfAbsent(name, Var::new);
    }

    /// Installs `value` as the root binding of `name` and returns the Var
    /// itself, the way Clojure's `def` evaluates to `#'user/name`. Called by the
    /// bytecode generated for `(def name value)`.
    public static Var def(String name, Object value) {
        Var var = var(name);
        var.bindRoot(value);
        return var;
    }

    /// Applies a built-in binary operator. A real Clojure would resolve the
    /// operator to an `IFn` and call it through `invokedynamic`.
    public static Object invokeOp(String op, Object a, Object b) {
        long x = asLong(op, a);
        long y = asLong(op, b);
        return switch (op) {
            case "+" -> x + y;
            case "-" -> x - y;
            case "*" -> x * y;
            case "/" -> divide(x, y);
            case "<" -> x < y;
            case ">" -> x > y;
            case "=" -> x == y;
            default -> throw new MocljException("Unknown op: " + op);
        };
    }

    /// Looks up an interned [Var], or `null` when the name was never `def`ed.
    public static Var lookupVar(String name) {
        return VARS.get(name);
    }

    /// Discards every binding. Intended for tests and for restarting a REPL.
    public static void clear() {
        VARS.clear();
    }

    private static long divide(long x, long y) {
        if (y == 0) {
            throw new MocljException("Divide by zero");
        }
        return x / y;
    }

    private static long asLong(String op, Object value) {
        if (value instanceof Number n) {
            return n.longValue();
        }
        throw new MocljException(op + " expects numbers but got: " + value);
    }
}
