package moclj;

import java.lang.constant.ClassDesc;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/// The runtime shared by every compiled class: a static registry of [Var]s plus
/// the handful of helpers that generated bytecode calls into.
///
/// The methods below are the compilation targets of [Compiler]; they are public
/// because generated classes invoke them with `invokestatic`.
public final class RT {

    static final ClassDesc CLASS_DESC = ClassDesc.of(RT.class.getName());

    private static final Map<String, Var> VARS = new ConcurrentHashMap<>();

    private RT() {
    }

    /// Interns `name` and installs `value` as its root binding. Called by the
    /// bytecode generated for `(def name value)`.
    public static Object bind(String name, Object value) {
        VARS.compute(name, (key, existing) -> {
            if (existing == null) {
                return new Var(key, value);
            }
            existing.bindRoot(value);
            return existing;
        });
        return value;
    }

    /// Reads the root binding of `name`. Called by the bytecode generated for a
    /// symbol reference.
    public static Object get(String name) {
        Var var = VARS.get(name);
        if (var == null) {
            throw new MocljException("Unable to resolve symbol: " + name + " in this context");
        }
        return var.deref();
    }

    /// Applies a built-in binary operator. A real Clojure would resolve the
    /// operator to an `IFn` and call it through `invokedynamic`.
    public static Object invokeOp(String op, Object a, Object b) {
        long x = asLong(op, a);
        long y = asLong(op, b);
        return switch (op) {
            case "+" -> x + y;
            case "-" -> x - y;
            case "*" -> x * y;
            case "/" -> divide(x, y);
            case "<" -> x < y;
            case ">" -> x > y;
            case "=" -> x == y;
            default -> throw new MocljException("Unknown op: " + op);
        };
    }

    /// Looks up an interned [Var], or `null` when the symbol is unbound.
    public static Var lookupVar(String name) {
        return VARS.get(name);
    }

    /// Discards every binding. Intended for tests and for restarting a REPL.
    public static void clear() {
        VARS.clear();
    }

    private static long divide(long x, long y) {
        if (y == 0) {
            throw new MocljException("Divide by zero");
        }
        return x / y;
    }

    private static long asLong(String op, Object value) {
        if (value instanceof Number n) {
            return n.longValue();
        }
        throw new MocljException(op + " expects numbers but got: " + value);
    }
}
