package moclj;

import java.lang.constant.ClassDesc;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/// The runtime shared by every compiled class: the intern table mapping names
/// to [Var]s plus the handful of helpers that generated bytecode calls into.
///
/// The table maps a name to a Var, never straight to a value, so the value of a
/// name can change while its container stays the same object.
///
/// The methods below are the compilation targets of [Compiler]; they are public
/// because generated classes invoke them with `invokestatic`.
public final class RT {

    static final ClassDesc CLASS_DESC = ClassDesc.of(RT.class.getName());

    private static final Map<String, Var> VARS = new ConcurrentHashMap<>();

    private RT() {
    }

    /// Returns the Var interned under `name`, creating an unbound one when the
    /// name is new. Called once per referenced name from the `<clinit>` of a
    /// generated class, which then caches the result in a static field.
    public static Var var(String name) {
        return VARS.computeIfAbsent(name, Var::new);
    }

    /// Installs `value` as the root binding of `name` and returns the Var
    /// itself, the way Clojure's `def` evaluates to `#'user/name`. Called by the
    /// bytecode generated for `(def name value)`.
    public static Var def(String name, Object value) {
        Var var = var(name);
        var.bindRoot(value);
        return var;
    }

    /// The vector holding `items`, the value of a `[...]` literal.
    public static PersistentVector vector(Object... items) {
        return PersistentVector.of(items);
    }

    /// `coll` with `value` appended, a new vector sharing its structure with
    /// `coll`, which is left untouched.
    public static PersistentVector conj(Object coll, Object value) {
        return asVector("conj", coll).conj(value);
    }

    /// The element of `coll` at `index`.
    public static Object nth(Object coll, Object index) {
        return asVector("nth", coll).nth((int) asLong("nth", index));
    }

    /// `coll` with `index` replaced by `value`, again as a new vector.
    public static PersistentVector assoc(Object coll, Object index, Object value) {
        return asVector("assoc", coll).assoc((int) asLong("assoc", index), value);
    }

    /// The number of elements in `coll`.
    public static Object count(Object coll) {
        return (long) asVector("count", coll).size();
    }

    /// Applies a built-in binary operator. A real Clojure would resolve the
    /// operator to an `IFn` and call it through `invokedynamic`.
    public static Object invokeOp(String op, Object a, Object b) {
        if (op.equals("=")) {
            return equiv(a, b);
        }
        long x = asLong(op, a);
        long y = asLong(op, b);
        return switch (op) {
            case "+" -> x + y;
            case "-" -> x - y;
            case "*" -> x * y;
            case "/" -> divide(x, y);
            case "<" -> x < y;
            case ">" -> x > y;
            default -> throw new MocljException("Unknown op: " + op);
        };
    }

    /// Looks up an interned [Var], or `null` when the name was never `def`ed.
    public static Var lookupVar(String name) {
        return VARS.get(name);
    }

    /// Discards every binding. Intended for tests and for restarting a REPL.
    public static void clear() {
        VARS.clear();
    }

    private static long divide(long x, long y) {
        if (y == 0) {
            throw new MocljException("Divide by zero");
        }
        return x / y;
    }

    private static long asLong(String op, Object value) {
        if (value instanceof Number n) {
            return n.longValue();
        }
        throw new MocljException(op + " expects numbers but got: " + value);
    }

    private static PersistentVector asVector(String fn, Object value) {
        if (value instanceof PersistentVector v) {
            return v;
        }
        throw new MocljException(fn + " expects a vector but got: " + Repl.print(value));
    }

    /// Equality across the supported types: numbers compare by value, anything
    /// else - vectors included - by `equals`.
    private static boolean equiv(Object a, Object b) {
        if (a instanceof Number x && b instanceof Number y) {
            return x.longValue() == y.longValue();
        }
        return Objects.equals(a, b);
    }
}
